# Generated by Django 3.2 on 2021-04-15 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graphql_app', '0002_task_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de finalizacion de la tarea'),
        ),
    ]
