# Generated by Django 3.2 on 2021-04-15 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graphql_app', '0003_task_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(max_length=250, verbose_name='Descripcion'),
        ),
    ]
